// import "./globals.css";
// import AuthProvider from "@/app/context/AuthProvider";
// import type { Metadata } from "next";
// import { Toaster } from "@/components/ui/toaster"

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <AuthProvider>
//       <body >
//         {children}
//         <Toaster />
//       </body>
//       </AuthProvider>
//     </html>
//   );
// }

import "./globals.css";
import AuthProvider from "@/app/context/AuthProvider";
import type { Metadata } from "next";
import { Toaster } from "@/components/ui/toaster";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <body>
          <Navbar/>
          {children}
          <Toaster />
        </body>
      </AuthProvider>
    </html>
  );
}
